### PR TITLE
Addition of background color functionality

### PR DESCRIPTION
**Pull request by f3lin3**
In learning git I have been able to figure out how to squash my commits from #87 to support a background color option for https://github.com/ififfy/flipflip/issues/86 into a single commit.

### CODE REVIEW

**Comment by GoddessServant0** [comment]
Work looks good @f3lin3 , no problem making a new PR, it can take some time to get used to Git. 

One question before I merge. Why do we need extra BT constant? Why not just default to blurred background in the case no color is defined? 🤔 I'm one for reducing code if it's logically unnecessary. Is there a logical reason for needing that constant defined?

**Comment by f3lin3** [comment]
I was thinking about enhancement for the future with that BT constant.  For example - being able to have a background video or gif playing, or having an animated (eg. spinning background) etc.

**Comment by f3lin3** [comment]
I did wonder if we are doing the right thing to put the background color on the Effects Control Group. 
It may alternatively "fit" with the Images Control Group.  However being on the Effects Control Group for now does mean that it is available to change while the scene is running give the Effects Control Group from the SceneOptions sidebar.  Perhaps after feedback further changes can be made.

**Comment by GoddessServant0** [comment]
> Being able to have a background video or gif playing, or having an animated (eg. spinning background) etc.

Personally, I don't see much of a desire for this when you have an overlay. Moreover, with the current structure, this wouldn't work as the background is rendered with each image (so any gif/video would be restarted with every `ImagePlayer` rendering) 

I'm gunna go ahead and remove it for now, but we can add it back later if we decide to add more background options 😁

And I think it makes sense on the Effects, it's not modifying which images are playing, but the effect added to it 👍 

Thanks for all the help @f3lin3! Gunna make some slight adjustments and then I'll merge in

**Comment by GoddessServant0** [comment]
Also, @f3lin3 , do you know how to squash commits in git now? I'm happy to help teach you these kind of things, I just don't know where you're at 🙂

**Comment by f3lin3** [comment]
Thanks for the offer of GIT tutition :) It is very much appreciated!

Over the weekend I had a lot of fun getting to grips with GIT with:
1. Creating new local branches from specified commits
2. Merging committed changes between local branches
3. Pushing new local branches to GitHub
4. Enabling 2FA on Github
5. Squashing local commits and re working the commit commentary
6. Configuring GPG to generate signing keys
5. Embedding different credentials and signing keys in different git projects
etc... etc... etc...

I also have to learn React, Electron and Typescript - but I will get there!

In the dim and distant past (shortly after launch of Microsoft's TFS) I was lead architect and had management oversight of some very large international project migrations from different SCM systems into TFS to be able to retain integrity and certify accuracy of historical commits. (The exposed TFS Migration Interface at the time was limited/challenged so this involved considerable sidestepping of the interface and poking appropriate commit data and (cross references!) directly into the TFS database).

So I have rudimentary understanding of some SCM concepts if still "rather rusty" and until this year (2019) I had zero exposure to GIT!

**Comment by GoddessServant0** [comment]
Wow that must have been a challenge! I had only used SVN in the past for version control until my current job. Found Git is _so_ much better and actually a very intuitive and easy to use tool once you get used to it 😁 I'm new to React framework as well, but we're moving to TypeScript at work soon, so this is good early exposure for me.

Some things about git are _not_ intutitive (like when you create a local branch, there is no remote branch yet, so you have to set the tracking branch to the remote after the first push 😒) so if you ever have a specific question, feel free to ask 🙂

**Comment by GoddessServant0** [comment]
Also, it seems part of the logical requirement for the Background Types variable is the color input does not allow you select a "null" color, so there would be no way to select a blurred background 😕

**Comment by GoddessServant0** [comment]
Did a little code cleanup but all looks and works perfect! 👍 Great job

**Pull request merged**
