### PR TITLE
Emoji icons and standard font

### PR DESCRIPTION
**Pull request by f3lin3**
PR embeds Google open source fonts **Roboto-Light**, and **NotoColorEmoji** providing increased aesthetic cross platform consistency and removes the reliance on which system fonts users may have installed. 

**NotoColorEmoji** is however a big bloat to the project for just a handful of icons - so it is suggested that thought is given to which icons are really wanted/needed and we can then work out how to reduce the size of the font file - perhaps create a derivative font "**FlipFlipColorEmoji**" 

F3

### CODE REVIEW

**Comment by GoddessServant0** [comment]
Thanks for pulling this together @f3lin3 🙂 A few things

1. No reason to make a new PR if you have changes/improvements. PRs act as history of development, so if you make a new one, we lose that history. If it's on the same topic, just continue adding commits to the branch (no need to force push unless you are trying specifically to override existing work -- like rebasing) and change the title of the PR to be more specific.
2. This commit includes changes from #124 because it looks like you created your `Fonts` branch from the head of `VSCodeDebugging` and not `master`. No problem, just do `git checkout Fonts` and then `git rebase master` and _then_ force push (because you need to totally override the history in this case) -- I think this should work 🤔 
  * Something I wanted to mention, I'd highly recommend adding this to your `~/.bashrc`  (or w/e shell profile you use): ```alias gl='git log --oneline --graph --color --all --decorate'```
  * This will print a nice visual representation of the changes so you can easily see where branches split, joined, etc.
3. Please use the original characters I had for down-arrow and pencil:
```$emojiDownArrow: '\1F80B';
$emojiPencil: '\270E';```
4. Lastly, I'm not a _huge_ fan of this font. But given it's free, its a fantastic starting place. We can change it later if we find a better one 👍 

If you can make those adjustments (namely 2 & 3) I will be happy to merge 😁

**Comment by ififfy** [comment]
Can someone give a quick summary of why this is necessary? I like the Mac system font being the default font when running on a Mac.

**Comment by ififfy** [comment]
(By "this" I mean the whole font packaging thing.) If you're going to all this trouble to add emoji fonts, you might as well use a public domain PNG icon set instead.

**Comment by GoddessServant0** [comment]
@ififfy This is in relation to the comments in #120 (but not pertaining to the issue in the title)
Essentially, when I developed this, my system clearly had all the fonts necessary. But when I (and @f3lin3) tested on mac/linux, some of the icons were missing.

This is simply to ensure that all users have the icons present. It wasn't so much about 'emoji' as simple Unicode symbols, but yes we could use small PNG/SVGs for icons instead.

Is that your preference @ififfy ?

**Comment by ififfy** [comment]
I think it's certainly less complex to just use PNGs. Fonts are a big complex thing; it's hard to even know how many pixels large an emoji or character is, so using them as UI icons is problematic. Speaking from extensive experience here. :-)

**Comment by f3lin3** [comment]
@ififfy :
PNGs for a few icons should hopefully be a smaller footprint than a large font file of mostly unused emojis. Emoji's in a scale-able font may scale better - but I don't think we are doing any scaling of buttons with icons. 

As to the system font preferred on the Mac - I would point out that the look of FlipFlip's fonts varies considerably from Windows, Mac, Linux Distros, (and Raspberry PI !).  As a cross-platform user/tester I would personally prefer consistency in the look - regardless of what that look was - **Is it not possible to locate an open source Mac system like font, and embed that ?**

@GoddessServant0 :
> * Something I wanted to mention, I'd highly recommend adding this to your `~/.bashrc`  (or w/e shell profile you use): `alias gl='git log --oneline --graph --color --all --decorate'`

Thanks that will be very useful...

> 3\. Please use the original characters I had for down-arrow and pencil:
> 
> ```
> $emojiDownArrow: '\1F80B';
> $emojiPencil: '\270E';
> ```

FYI: In the particular font set: the pencil emoji '\270E' appears in B/W  and the down arrow '\1F80B' is blank.

In any event I think @ififfy wants PNGs not emojis. So the PR can be rejected.

**Comment by f3lin3** [comment]
$emojiPencil has been updated to the B/W version - I left the $emojiDownArrow as it was as '1F80B' is not in the attached emoji Font.



> 2\. This commit includes changes from #124 because it looks like you created your `Fonts` branch from the head of `VSCodeDebugging` and not `master`. No problem, just do `git checkout Fonts` and then `git rebase master` and _then_ force push (because you need to totally override the history in this case) -- I think this should work thinking

I tried the git re-basing dance etc...  - Regardless of if this PR is being rejected - I don't think it expunged the #124 ... ?

**Comment by ififfy** [comment]
The only people who use these kinds of apps across platforms are developers. Making apps is all about users. 😄 And users are happier when apps look somewhat like they belong. We might be making an Electron app out of expedience, but we can make small efforts to embrace platform differences.

OTOH, I do understand how drastically different fonts could be frustrating. What if we package just Roboto as a backup, and leave the Mac and Windows fonts in place?

**Comment by ififfy** [comment]
Looking at #120 for context, it seems it's all about the emojis anyway, so the font fallback might not be necessary.

**Comment by GoddessServant0** [comment]
> I would personally prefer consistency in the look - regardless of what that look was

I agree

> The only people who use these kinds of apps across platforms are developers. Making apps is all about users. 😄

😋 Hey I use it on both Mac and Windows! lol But totally agree about focusing on users.

> Looking at #120 for context, it seems it's all about the emojis anyway, so the font fallback might not be necessary.

I would say the look is slightly different between the two, so if it's not a big deal, I'd love if we could do:

> What if we package just Roboto as a backup, and leave the Mac and Windows fonts in place?

**Lets do that.**
@f3lin3 Can you change this PR to fulfill this? I will implement a separate PR with PNG icons (if you're ok with that).
[[ Just as a side note, this is just a friendly dev environment. You have no obligation here 😋 If you don't want to do something, that's np, just say so if not 😁 ]]

---

I think still making these icons PNGs would be smart on top of consistent font. (As Roboto does not have all the characters we would want to use necessary).

> FYI: In the particular font set: the pencil emoji '\270E' appears in B/W and the down arrow '\1F80B' is blank.

This point is moot, but just for clarification sake, yes I wanted those 🙂 [`'\1F80B'`](https://www.compart.com/en/unicode/U+1F80B) is a B/W down arrow and I prefer the B/W pencil [`'\270E'`](https://www.compart.com/en/unicode/U+270E)

> I tried the git re-basing dance etc... - Regardless of if this PR is being rejected - I don't think it expunged the #124 ... ?

I see... it's actually because the README _is part of_ the first commit (cd34634fdde5345d06dbfb361d735f7999a40e5b). Don't worry about it for now, we'll take care of it when we merge the PR. Probably how this happened was you _did_ reset to `master` from your previous work, but it was a soft reset. So when you went to do the Font work, you committed the Debug changes as well. I've done this myself a few times, so no worries. Just trying to help out 😉💕

**Comment by GoddessServant0** [comment]
Whoops... I didn't mean to push my changes to `master` but I did (a little tipsy 😋). PNG icons are implemented (684f1bbc38f8cd258c57a8d515b153dd4afdcd64) I opted for B/W icons because they just fit with the aesthetic a bit better, but we can update these later.

Don't worry about trying to solve all the git shit @f3lin3. As long as the changes you intended are clear I can fix the rest 👍

**Comment by f3lin3** [comment]
Agh - I thought I was getting there :) making the changes and now there are conflicting style.scss changes ahead of me....   Oh well - this is good experience. I guess I do a soft reset of my last commit to Fonts, a pull from ififfy:master, merge, and then force push to Fonts?

**Comment by GoddessServant0** [comment]
It would be helpful for me if I know exactly what to tell you. 😉 Are all your _local_ changes pushed to **your** git fork? i.e. If I'm looking at `f3lin3/master` is that the same as your local changes?

**Comment by GoddessServant0** [comment]
Sorry, looks like you are 👍 (I should've just verified the commit id already)

Ok... so here's what you want to do:
1. `git checkout master`  -- We need to update the master branch so we can rebase off of the new HEAD
2. `git pull upstream master` -- Pull my PNG change to your `master`. Btw, it's common practice to name the main fork "upstream" but if you named it something else, just use that name here. 
3. `git checkout Fonts` -- We need to checkout Fonts again so we can rebase it off of the new `master`
4. `git rebase master` -- Now its like `Fonts` was always done after `master`
5. `git push origin master --force` -- Since we rebased our branch, all commits are new, we need to force push

I see you already solved it, but thought I'd post this for you anyway 😉

**Comment by f3lin3** [comment]
Thank you! especially for the git tutorial above.  It must be so frustrating for you and ififfy to have git rookie like me getting in your way - so I appreciate the guidance.

**Comment by GoddessServant0** [comment]
Not at all 😘 We all had to start somewhere right? For the record, I used [https://learngitbranching.js.org/](https://learngitbranching.js.org/) when I was first learning Git and it was super helpful. Check it out if you have some time 👍

**Comment by ififfy** [comment]
I learned from this book: https://git-scm.com/book/en/v2

Git is the worst version control system, except for all the other ones. You're doing fine.

**Pull request merged**
