### PR TITLE
Fix to Cross-fade bug #78

### PR DESCRIPTION
**Pull request by f3lin3**
reference: https://github.com/ififfy/flipflip/issues/78 

Created:   ImagePlayer.state.nextImageID=0
Incremented: ImagePlayer  render() method 
Used in the key:  key={this.state.nextImageID.toString()

not sure if this is exactly the way you wanted it doing - it works on my testing.

### CODE REVIEW

**Comment by ififfy** [comment]
I don't think this is correct; the idea is that you don't want image DOM elements being replaced, and one key === one DOM element.

It is actually legal in JS to attach random properties to things, you just have to get TypeScript out of the way by casting to `any` a bunch. :-)

**Comment by ififfy** [comment]
If I make two elements `` and ``, and then replace them with `` and ``, React will create fresh elements and CSS animations will be interrupted.

**Comment by GoddessServant0** [comment]
I just tried incrementing it when `readyToDisplay` or `pastAndLatest` is set and neither of those worked 🤔

**Comment by GoddessServant0** [comment]
I'm unfortunately using `img.alt` to hold the gif timing 😕 Can we add arbitrary properties to `Image`? I guess we could make a wrapper class, but I'm not a fan of that

**Comment by ififfy** [comment]
Again, just cast to `any` and go wild. 😄 `(img as any).whatever = 'whatever'`

**Comment by GoddessServant0** [comment]
Fixed 👍 Works now (and doesn't cross-fade to the same image over and over)

**Pull request merged**
